top/staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('order/<int:pk>', views.order, name='order'),
    path('order_edit/<int:pk>', views.order_edit, name='order_edit'),
    path('add_product/', views.add_product, name='add_product'),
]

top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

top/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password')
]

top/staff/models.py
from django.db import models

# Create your models here.

top/staff/forms.py
from django import forms
from .bulma_mixin import BulmaMixin
from store.models import *


class OrderForm(BulmaMixin, forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Напишите адрес доставки'
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Напишите номер телефона'
    }))
    status = forms.ChoiceField(choices=STATUS)

    class Meta:
        model = Order
        fields = ['address', 'phone', 'status']



class ProductForm(BulmaMixin, forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Напишите наименование товара'
    }), required=False)
    slug = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Придумайте уникальный идентификатор'
    }), required=False)
    description = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Описание продукта'
    }), required=False)
    price = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите цену товара'
    }), required=False)
    is_new = forms.CharField(widget=forms.CheckboxInput(), label='Новинка', required=False)
    is_discounted = forms.CharField(widget=forms.CheckboxInput(), label='Скидка', required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Product
        fields = [
            'name',
            'slug',
            'description',
            'price',
            'is_new',
            'is_discounted',
            'category',
            'brand',
            'image'
        ]

top/staff/views.py
from django.shortcuts import render, redirect
from store.models import *
from .forms import OrderForm, ProductForm


def home(request):
    orders = Order.objects.all()
    action = request.GET.get('filter')
    if action == 'new':
        orders = orders.filter(status='Создан')
    elif action == 'get':
        orders = orders.filter(status='Принят в работу')
    elif action == 'send':
        orders = orders.filter(status='В пути')
    elif action == 'done':
        orders = orders.filter(status='Доставлен')
    return render(request, 'admin.html', {'orders': orders})


def order(request, pk):
    order_data = Order.objects.get(pk=pk)
    return render(request, 'order.html', {'order': order_data})


def order_edit(request, pk):
    order_data = Order.objects.get(pk=pk)
    form = OrderForm(request.POST or None, instance=order_data)
    if form.is_valid():
        form.save()
        return redirect('staff:order', pk=pk)
    return render(request, 'order_edit.html', {'form': form})


def add_product(request):
    form = ProductForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('staff:home')
    print(40)
    return render(request, 'add_product.html', {'form': form})

top/staff/templates/add_product.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-5">
                    <form class="box" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == 'category' or field.name == 'brand' %}
                                <label class="label">
                                    {{ field.label }}
                                </label>
                                <div class="select">
                                    {{ field }}
                                </div>
                            {% else %}
                                <div class="field">
                                    <label class="label">
                                        {{ field.label }}
                                    </label>
                                    <div class="control">{{ field }}</div>
                                </div>
                            {% endif %}
                            {% if form.errors %}
                                <ul>
                                    {% for error in form.errors.values %}
                                        <li class="has-text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        {% endfor %}
                        <div class="has-text-centered">
                            <button class="button is-info is-fullwidth">
                                Добавить товар
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

top/staff/templates/admin.html
{% extends 'admin_layout.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="title has-text-centered">Заказы</div>
            <div class="columns is-multiline is-centered">
                {% for order in orders %}
                    <div class="column is-3">
                        <div class="box">
                            <div class="title is-5 has-text-centered">
                                Заказ #{{ order.pk }}
                                <span class="tag is-meduim is-success">
                            {{ order.status }}
                        </span>
                            </div>
                            <div class="subtitle">
                                Покупатель:
                                <span class="is-italic has-text-weight-bold">
                            {{ order.customer }}
                        </span>
                            </div>
                            <div class="buttons">
                                <a class="button is-fullwidth" href="{% url 'staff:order' order.pk %}">
                                    Перейти
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

top/staff/templates/admin_layout.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>

<body>
<nav class="navbar">
    <div class="navbar-brand">
        <a href="{% url 'staff:home' %}" class="navbar-item">
            <ion-icon name="person-outline"></ion-icon>
        </a>
    </div>
    <div class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'store:home' %}" class="navbar-item">
                Страница магазина
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
                <div class="navbar-link">
                    Отсортировать заказы
                </div>
                <div class="navbar-dropdown">
                    <a href="{% url 'staff:home' %}" class="navbar-item">
                        Все заказы
                    </a>
                    <a href="{% url 'staff:home' %}?filter=new" class="navbar-item">
                        Новые заказы
                    </a>
                    <a href="{% url 'staff:home' %}?filter=get" class="navbar-item">
                        Принятые заказы
                    </a>
                    <a href="{% url 'staff:home' %}?filter=send" class="navbar-item">
                        Отправленные заказы
                    </a>
                    <a href="{% url 'staff:home' %}?filter=done" class="navbar-item">
                        Выполненные заказы
                    </a>
                </div>

            </div>
            <a href="{% url 'staff:add_product' %}" class="navbar-item">
                Добавить товар
            </a>
        </div>
        <div class="navbar-end">
            <a href="{% url 'users:sign_out' %}" class="navbar-item">
                Выйти
            </a>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>

</html>

top/staff/templates/order.html
{% extends 'admin_layout.html' %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="title has-text-centered">
            Заказ №{{order.pk}}
        </div>
        <div class="columns is-centered is-vcentered">
            <div class="column is-7 ">
                <div class="box">
                    <table class="table is-fullwidth">
                        <thead>
                            <tr>
                                <th>Имя товара</th>
                                <th>Кол-во</th>
                                <th>Общая сумма</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in order.order_products.all %}
                            <tr>
                                <td>{{ product }}</td>
                                <td>{{ product.amount }} шт</td>
                                <td>{{ product.total }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3" class="has-text-right has-text-weight-bold">
                                    Общая сумма: {{ order.total_price }} рублей
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class="column">
                <div class="box">
                    <div class="title is-3">
                        Информация о покупателе
                    </div>
                    <div class="title is-4">
                        <ion-icon name="person" class="mr-4"></ion-icon>
                        {{order.customer.username}}
                    </div>
                    <div class="title is-4">
                        <ion-icon name="home" class="mr-4"></ion-icon>
                        {{order.address}}
                    </div>
                    <div class="title is-4">
                        <ion-icon name="call" class="mr-4"></ion-icon>
                        {{order.phone}}
                    </div>
                    <div class="title is-4">
                        <ion-icon name="information-circle"></ion-icon>
                        {{ order.status }}
                    </div>
                    <div class="title is-4">
                        <ion-icon name="chatbubbles-outline"></ion-icon>
                        {{ order.comment }}
                    </div>
                    <a href="{% url 'staff:order_edit' order.pk %}" class="button is-fullwidth">
                        Отредактировать заказ
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

top/staff/templates/order_edit.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-5">
                    <form class="box" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == 'status' %}
                                <div class="select">
                                    {{ field }}
                                </div>
                            {% else %}
                                <div class="field">
                                    <div class="control">{{ field }}</div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="has-text-centered">
                            <button class="button is-info is-fullwidth">
                                Отредактировать
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}