top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

top/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password')
]

top/users/models.py
from django.db import models

# Create your models here.

top/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .bulma_mixin import BulmaMixin


class SignInForm(BulmaMixin, AuthenticationForm):
    username = forms.CharField(label='Напишите никнейм')
    password = forms.CharField(
        widget=forms.PasswordInput(), label='Напишите пароль')

    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField(label='Придумайте никнейм')
    password1 = forms.CharField(
        widget=forms.PasswordInput(), label='Придуймайте пароль')
    password2 = forms.CharField(
        widget=forms.PasswordInput(), label='Повторите пароль')
    email = forms.EmailField(label='Введите адрес почты')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class EditProfileForm(BulmaMixin, forms.ModelForm):
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')
    username = forms.CharField(label='Никнейм')
    email = forms.EmailField(label='Адрес почты')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class ResetPasswordForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(), label='Текущий пароль')
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(), label='Новый пароль')
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(), label='Повторите новый пароль'
    )

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

top/users/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, logout
from store.models import *
from django.contrib.auth import update_session_auth_hash


def sign_in(request):
    form = SignInForm(data=request.POST or None)
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        connect_data(request)

        if request.GET.get('next'):
            return redirect(request.GET.get('next'))

        return redirect('store:home')
    return render(request, 'sign_in.html', {'form': form})


def sign_up(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('users:sign_in')
    return render(request, 'sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def connect_data(request):
    token = request.COOKIES['csrftoken']
    guest = Guest.objects.filter(token=token)
    cart_items = CartItem.objects.filter(guest=guest[0]) if guest else []

    for item in cart_items:
        item.customer = request.user
        item.guest = None
        item.save()
    guest.delete()


def edit_profile(request):
    form = EditProfileForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('store:home')
    return render(request, 'edit_profile.html', {'form': form})


def reset_password(request):
    form = ResetPasswordForm(request.user, request.POST or None)
    if form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('users:sign_in')
    return render(request, 'reset_password.html', {'form': form})

top/users/templates/edit_profile.html
{% extends 'base_layout.html' %}

{% block auth %}
<div class="section">
    <div class="container">
        <div class="columns is-centered ">
            <div class="column is-4">
                <div class="box has-background-info-light">
                    <form method="post">
                        <div class="title is-4">Редактирование профиля</div>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            <label class="label" for="{{field.id_for_label}}">
                                {{ field.label }}
                            </label>
                            <div class="control">
                                {{field}}
                            </div>
                        </div>
                        {% endfor %}
                        {% if form.errors %}
                        <ul>
                            {% for error in form.errors.values %}
                            <li class="has-text-danger">{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <button class="button is-dark">Изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

top/users/templates/reset_password.html
{% extends 'base_layout.html' %}

{% block auth %}
<div class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <div class="box">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            <label for="{{field.id_for_label}}" class="label">
                                {{field.label}}
                            </label>
                            <div class="control">
                                {{field}}
                            </div>
                        </div>
                        {% endfor %}
                        <button class="button is-success">
                            Изменить пароль
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

top/users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block auth %}
<div class="columns is-centered mt-3">
    <div class="column is-4">
        <div class="box has-background-info-light">
            <form method="post">
                <div class="title is-2 has-text-centered">
                    Вход
                </div>
                {% csrf_token %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">
                        {{field.label}}
                    </label>
                    <div class="control">
                        {{field}}
                    </div>
                </div>
                {% endfor %}

                {% if form.errors %}
                <ul>
                    {% for error in form.errors.values %}
                    <li class="has-text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <div class="has-text-centered">
                    <button class="button is-success">
                        Войти
                    </button>
                </div>
                <div class="content has-text-centered  mt-4">
                    <span>Еще не зарегистрировались?</span>
                    <br><br>
                    <a href="{% url 'users:sign_up' %}">
                        Создать аккаунт
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

top/users/templates/sign_up.html
{% extends 'base_layout.html' %}

{% block auth %}
<div class="columns is-centered mt-3">
    <div class="column is-4">
        <div class="box has-background-info-light">
            <form method="post">
                <div class="title is-2 has-text-centered">
                    Регистрация
                </div>
                {% csrf_token %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">
                        {{field.label}}
                    </label>
                    <div class="control">
                        {{field}}
                    </div>
                </div>
                {% endfor %}

                {% if form.errors %}
                <ul>
                    {% for error in form.errors.values %}
                    <li class="has-text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <div class="has-text-centered">
                    <button class="button is-success">
                        Отправить
                    </button>
                </div>
                <div class="content has-text-centered  mt-4">
                    <span>Уже есть аккаунт</span>
                    <br><br>
                    <a href="{% url 'users:sign_in' %}">
                        Авторизоваться
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}